### ISSUE TITLE
Create Tax Microservice using FastAPI

### ISSUE THREAD

**Issue by Tamas99** [Tamas99/PurchaseEventsApp#3]
The second microservice.

This will calculate new taxes after each house purchase event and provide an endpoint for querying this information in order to save the purchase events with the calculated house prices including the taxes.

Required endpoints:
- [x] get specific tax
- [x] get all taxes
- [x] delete all taxes

Other functionalities:
- [x] connect to Kafka to listen for incoming purchase events

**Comment by Deepanshusaxena1** [comment]
Hi @Tamas99 I want to work on this ticket, can you please assign this issue to me?

**Comment by Tamas99** [comment]
Hello,

Can you see my message if I write here?

B.T.

**Comment by Deepanshusaxena1** [comment]
Hi, I can see your message.

**Comment by Tamas99** [comment]
Okay. May I ask you to fork this project, and then you can work on the issues? I shouldn't assign directly any issue to you, because this is a Dissertation project and it will be not accepted if I'm not the only one working on it. I hope you understand.

Your advices and ideas would still interest me, though, if you have any. Also, it's a possible solution that I create a separate branch, and you will work on that one.
